const
  BOTNAME_DEFAULT = 'Carik';
  
  CLARIFAI_TOKEN = 'clarifai/default/token';
  CLARIFAI_CLIENTID = 'clarifai/default/client_id';
  CLARIFAI_CLIENTSECRET = 'clarifai/default/client_secret';
  TELEGRAM_TOKEN = 'telegram/default/token';
  FACEBOOK_TOKEN = 'facebook/default/token';
  WITAI_TOKEN = 'witai/default/token';
  GOOGLE_KEY = 'google/default/key';
  ZOMATO_KEY = 'zomato/default/key';
  YANDEX_KEY = 'yandex/default/key';
  COGNITIVE_OCR_TOKEN = 'cognitive/ocr/key';
  OPENWEATHERMAP_KEY = 'openweathermap/default/key';
  APIXU_KEY = 'apixu/default/key';
  IBACOR_TOKEN = 'ibacor/default/token';

  KLAUDLESS_APPID = 'klaudless/default/appid';
  KLAUDLESS_APIKEY = 'klaudless/default/apikey';
  KLAUDLESS_CALENDAR_ACCOUNTID = 'klaudless/default/calendar_accountid';
  KLAUDLESS_CALENDAR_ID = 'klaudless/default/calendar_id';

  MASKOFA_SHALAT_SESSIONID = 'maskofa/jadwalshalat/sessionid';
  MASKOFA_SHALAT_CITYLISTS = 'maskofa/jadwalshalat/citylists';

  VOICE_TMP_PATH = 'ztemp/voice/';

  CARIK_TTS_URL = 'carik/tts_url';
