const
  BOTNAME_DEFAULT = 'Carik';
  CONFIG_BOTNAME = 'ai/default/name';
  CLARIFAI_TOKEN = 'clarifai/default/token';
  CLARIFAI_CLIENTID = 'clarifai/default/client_id';
  CLARIFAI_CLIENTSECRET = 'clarifai/default/client_secret';

  CUSTOMVISION_KEY = 'customvision/default/key';
  CUSTOMVISION_URL = 'customvision/default/url';

  TELEGRAM_TOKEN = 'telegram/default/token';
  FACEBOOK_TOKEN = 'facebook/default/token';
  WITAI_TOKEN = 'witai/default/token';
  GOOGLE_KEY = 'google/default/key';
  GOOGLEANALYTICS_TRACKING_ID = 'googleanalytics/default/tracking_id';
  ZOMATO_URL = 'zomato/default/url';
  ZOMATO_KEY = 'zomato/default/key';
  YANDEX_KEY = 'yandex/default/key';
  COGNITIVE_OCR_TOKEN = 'cognitive/ocr/key';
  OPENWEATHERMAP_KEY = 'openweathermap/default/key';
  APIXU_KEY = 'apixu/default/key';
  IBACOR_TOKEN = 'ibacor/default/token';
  RAJAONGKIR_TOKEN = 'rajaongkir/default/key';

  PORTALPULSA_USERID = 'PortalPulsa/default/userid';
  PORTALPULSA_KEY = 'PortalPulsa/default/key';
  PORTALPULSA_SECRET = 'PortalPulsa/default/secret';



  KLAUDLESS_APPID = 'klaudless/default/appid';
  KLAUDLESS_APIKEY = 'klaudless/default/apikey';
  KLAUDLESS_CALENDAR_ACCOUNTID = 'klaudless/default/calendar_accountid';
  KLAUDLESS_CALENDAR_ID = 'klaudless/default/calendar_id';

  MASKOFA_SHALAT_SESSIONID = 'maskofa/jadwalshalat/sessionid';
  MASKOFA_SHALAT_CITYLISTS = 'maskofa/jadwalshalat/citylists';

  MSBOTFRAMEWORK_CLIENT_ID = 'msbotframework/default/client_id';
  MSBOTFRAMEWORK_CLIENT_SECRET = 'msbotframework/default/client_secret';

  FFMPEG_PATH = 'systems/ffmpeg_path';
  VOICE_TMP_PATH = 'ztemp/voice/';

  CMD_FULL_IMAGE_ANALYZE = 'full image analyze';
  CMD_IMAGE_TRANSLATION = 'image translation';

  CARIK_TTS_URL = 'carik/tts_url';

  RUMAH123_API_URL = 'rumah123/default/api_url';
  RUMAH123_API_CLIENT_TYPE = 'rumah123/default/api_client_type';
  RUMAH123_LISTING_MAX = 3;

  PAJAKMOTOR_API = 'pajakmotor/api_url';

